spring:
  application:
    name: FinDiary
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.35.27:3306/kwdb
    username: kw
    password: poi098)(*
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kwfw.findiary.model
logging:
  level:
    com.kwfw.findiary.mapper: DEBUG
    com.zaxxer.hikari: WARN